version: '3.8'
services:
  postgres:
    container_name: connect-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - connect_network
      
  mongo:
    container_name: connect-mongo
    image: mongo:4.2-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - connect_network

  neo4j:
    container_name: connect-neo4j
    image: neo4j:5.13-community
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/123
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins
    networks:
      - connect_network
    
networks:
  connect_network:
    name: connect-network
