CREATE DATABASE emp;
CREATE USER emp_r WITH PASSWORD '123';
CREATE USER emp_w WITH PASSWORD '123';
GRANT CONNECT ON DATABASE emp TO emp_r;
GRANT CONNECT ON DATABASE emp TO emp_w;

\c emp;

CREATE EXTENSION pgcrypto;

CREATE TABLE IF NOT EXISTS titlings(
	id INTEGER GENERATED ALWAYS AS IDENTITY,
	ehid TEXT NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE DEFAULT NULL,
	title TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	CONSTRAINT pk_titlings PRIMARY KEY(id)
);
GRANT SELECT ON titlings TO emp_r;
GRANT SELECT, UPDATE, INSERT, DELETE ON titlings TO emp_w;

CREATE TABLE IF NOT EXISTS gradings(
	id INTEGER GENERATED ALWAYS AS IDENTITY,
	ehid TEXT NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE DEFAULT NULL,
	grade TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	CONSTRAINT pk_gradings PRIMARY KEY(id)
);
GRANT SELECT ON gradings TO emp_r;
GRANT SELECT, UPDATE, INSERT, DELETE ON gradings TO emp_w;
